/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _rootNotFoundRouteImport } from './routes/__root.notFound'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedWorkspaceIndexRouteImport } from './routes/_protected/workspace/index'
import { Route as ProtectedWorkspaceNoWorkspacesRouteImport } from './routes/_protected/workspace/no-workspaces'
import { Route as ProtectedWorkspaceWorkspaceIdLayoutRouteImport } from './routes/_protected/workspace/$workspaceId/_layout'
import { Route as ProtectedWorkspaceWorkspaceIdLayoutIndexRouteImport } from './routes/_protected/workspace/$workspaceId/_layout/index'
import { Route as ProtectedWorkspaceWorkspaceIdLayoutThreadThreadIdRouteImport } from './routes/_protected/workspace/$workspaceId/_layout/thread/$threadId'

const _rootNotFoundRoute = _rootNotFoundRouteImport.update({
  id: '/__root/notFound',
  path: '/notFound',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedWorkspaceIndexRoute = ProtectedWorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedWorkspaceNoWorkspacesRoute =
  ProtectedWorkspaceNoWorkspacesRouteImport.update({
    id: '/workspace/no-workspaces',
    path: '/workspace/no-workspaces',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedWorkspaceWorkspaceIdLayoutRoute =
  ProtectedWorkspaceWorkspaceIdLayoutRouteImport.update({
    id: '/workspace/$workspaceId/_layout',
    path: '/workspace/$workspaceId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedWorkspaceWorkspaceIdLayoutIndexRoute =
  ProtectedWorkspaceWorkspaceIdLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedWorkspaceWorkspaceIdLayoutRoute,
  } as any)
const ProtectedWorkspaceWorkspaceIdLayoutThreadThreadIdRoute =
  ProtectedWorkspaceWorkspaceIdLayoutThreadThreadIdRouteImport.update({
    id: '/thread/$threadId',
    path: '/thread/$threadId',
    getParentRoute: () => ProtectedWorkspaceWorkspaceIdLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notFound': typeof _rootNotFoundRoute
  '/workspace/no-workspaces': typeof ProtectedWorkspaceNoWorkspacesRoute
  '/workspace/': typeof ProtectedWorkspaceIndexRoute
  '/workspace/$workspaceId': typeof ProtectedWorkspaceWorkspaceIdLayoutRouteWithChildren
  '/workspace/$workspaceId/': typeof ProtectedWorkspaceWorkspaceIdLayoutIndexRoute
  '/workspace/$workspaceId/thread/$threadId': typeof ProtectedWorkspaceWorkspaceIdLayoutThreadThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notFound': typeof _rootNotFoundRoute
  '/workspace/no-workspaces': typeof ProtectedWorkspaceNoWorkspacesRoute
  '/workspace': typeof ProtectedWorkspaceIndexRoute
  '/workspace/$workspaceId': typeof ProtectedWorkspaceWorkspaceIdLayoutIndexRoute
  '/workspace/$workspaceId/thread/$threadId': typeof ProtectedWorkspaceWorkspaceIdLayoutThreadThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/__root/notFound': typeof _rootNotFoundRoute
  '/_protected/workspace/no-workspaces': typeof ProtectedWorkspaceNoWorkspacesRoute
  '/_protected/workspace/': typeof ProtectedWorkspaceIndexRoute
  '/_protected/workspace/$workspaceId/_layout': typeof ProtectedWorkspaceWorkspaceIdLayoutRouteWithChildren
  '/_protected/workspace/$workspaceId/_layout/': typeof ProtectedWorkspaceWorkspaceIdLayoutIndexRoute
  '/_protected/workspace/$workspaceId/_layout/thread/$threadId': typeof ProtectedWorkspaceWorkspaceIdLayoutThreadThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/notFound'
    | '/workspace/no-workspaces'
    | '/workspace/'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/'
    | '/workspace/$workspaceId/thread/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/notFound'
    | '/workspace/no-workspaces'
    | '/workspace'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/thread/$threadId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/__root/notFound'
    | '/_protected/workspace/no-workspaces'
    | '/_protected/workspace/'
    | '/_protected/workspace/$workspaceId/_layout'
    | '/_protected/workspace/$workspaceId/_layout/'
    | '/_protected/workspace/$workspaceId/_layout/thread/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  _rootNotFoundRoute: typeof _rootNotFoundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__root/notFound': {
      id: '/__root/notFound'
      path: '/notFound'
      fullPath: '/notFound'
      preLoaderRoute: typeof _rootNotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/workspace/': {
      id: '/_protected/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof ProtectedWorkspaceIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/workspace/no-workspaces': {
      id: '/_protected/workspace/no-workspaces'
      path: '/workspace/no-workspaces'
      fullPath: '/workspace/no-workspaces'
      preLoaderRoute: typeof ProtectedWorkspaceNoWorkspacesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/workspace/$workspaceId/_layout': {
      id: '/_protected/workspace/$workspaceId/_layout'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof ProtectedWorkspaceWorkspaceIdLayoutRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/workspace/$workspaceId/_layout/': {
      id: '/_protected/workspace/$workspaceId/_layout/'
      path: '/'
      fullPath: '/workspace/$workspaceId/'
      preLoaderRoute: typeof ProtectedWorkspaceWorkspaceIdLayoutIndexRouteImport
      parentRoute: typeof ProtectedWorkspaceWorkspaceIdLayoutRoute
    }
    '/_protected/workspace/$workspaceId/_layout/thread/$threadId': {
      id: '/_protected/workspace/$workspaceId/_layout/thread/$threadId'
      path: '/thread/$threadId'
      fullPath: '/workspace/$workspaceId/thread/$threadId'
      preLoaderRoute: typeof ProtectedWorkspaceWorkspaceIdLayoutThreadThreadIdRouteImport
      parentRoute: typeof ProtectedWorkspaceWorkspaceIdLayoutRoute
    }
  }
}

interface ProtectedWorkspaceWorkspaceIdLayoutRouteChildren {
  ProtectedWorkspaceWorkspaceIdLayoutIndexRoute: typeof ProtectedWorkspaceWorkspaceIdLayoutIndexRoute
  ProtectedWorkspaceWorkspaceIdLayoutThreadThreadIdRoute: typeof ProtectedWorkspaceWorkspaceIdLayoutThreadThreadIdRoute
}

const ProtectedWorkspaceWorkspaceIdLayoutRouteChildren: ProtectedWorkspaceWorkspaceIdLayoutRouteChildren =
  {
    ProtectedWorkspaceWorkspaceIdLayoutIndexRoute:
      ProtectedWorkspaceWorkspaceIdLayoutIndexRoute,
    ProtectedWorkspaceWorkspaceIdLayoutThreadThreadIdRoute:
      ProtectedWorkspaceWorkspaceIdLayoutThreadThreadIdRoute,
  }

const ProtectedWorkspaceWorkspaceIdLayoutRouteWithChildren =
  ProtectedWorkspaceWorkspaceIdLayoutRoute._addFileChildren(
    ProtectedWorkspaceWorkspaceIdLayoutRouteChildren,
  )

interface ProtectedRouteChildren {
  ProtectedWorkspaceNoWorkspacesRoute: typeof ProtectedWorkspaceNoWorkspacesRoute
  ProtectedWorkspaceIndexRoute: typeof ProtectedWorkspaceIndexRoute
  ProtectedWorkspaceWorkspaceIdLayoutRoute: typeof ProtectedWorkspaceWorkspaceIdLayoutRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedWorkspaceNoWorkspacesRoute: ProtectedWorkspaceNoWorkspacesRoute,
  ProtectedWorkspaceIndexRoute: ProtectedWorkspaceIndexRoute,
  ProtectedWorkspaceWorkspaceIdLayoutRoute:
    ProtectedWorkspaceWorkspaceIdLayoutRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  _rootNotFoundRoute: _rootNotFoundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
