name: merge-develop-to-deployment

on:
  push:
    branches:
      - develop

jobs:
  merge-develop-into-deployments:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch origin +refs/heads/*:refs/remotes/origin/*

      - name: Ensure deployments/develop exists locally
        run: |
          if git show-ref --verify --quiet refs/heads/deployments/develop; then
            git checkout deployments/develop
          else
            # create local branch tracking the remote
            git checkout -b deployments/develop origin/deployments/develop
          fi

      - name: Merge develop into deployments/develop
        run: |
          # Merge the latest develop into deployments/develop, preserving deployment-only commits
          git merge origin/develop --no-edit

      - name: Push updated deployments/develop
        run: git push origin deployments/develop

      - name: Show result
        run: |
          echo "Latest merge commit:"
          git --no-pager log --oneline -n 5
