name: Sync develop → deployments/develop

on:
  push:
    branches: [develop]

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub App token
        id: app
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app.outputs.token }}

      - name: Configure git actor
        run: |
          git config user.name "ci-bot"
          git config user.email "ci-bot@users.noreply.github.com"

      - name: Merge develop into deployments/develop
        run: |
          git fetch origin deployments/develop:deployments/develop || git branch deployments/develop origin/deployments/develop
          git checkout deployments/develop
          git merge --no-ff origin/develop -m "Sync develop → deployments/develop"
          git push https://x-access-token:${{ steps.app.outputs.token }}@github.com/${{ github.repository }}.git HEAD:deployments/develop
